### ISSUE TITLE
Usage in colab

### ISSUE THREAD

**Issue by ashkanrdn** [smartcrop/smartcrop.py#19]
I am trying to use the library in colab but I am getting an error that smartcrop i snot defined even installation is successful.

**Comment by RobinDeBock** [comment]
Indeed, I stumbled upon the same problem

**Comment by RobinDeBock** [comment]
> I am trying to use the library in colab but I am getting an error that smartcrop i snot defined even installation is successful.

Use this code block to install and use the library:
`!pip3 install smartcrop
import site
site.main()
import smartcrop`

I got this from: https://stackoverflow.com/questions/57838013/modulenotfounderror-after-successful-pip-install-in-google-colaboratory
