### ISSUE TITLE
how to get image cordinates  like the smartcrop.js?

### ISSUE THREAD

**Issue by krishnakatyal** [smartcrop/smartcrop.py#20]
EXAMPLE:

{topCrop: {x: 300, y: 200, height: 200, width: 200}}

**Comment by kaypon** [comment]
I was able to pull it out of the result with the demo example code:

```
import json
import sys

import smartcrop
from PIL import Image

image = Image.open('999.jpg')

sc = smartcrop.SmartCrop()
result = sc.crop(image, 1440, 960)
print(result['top_crop'])
```

Prints:
`{'x': 32, 'y': 0, 'width': 1099, 'height': 733, 'score': {'detail': 98.19757825868165, 'saturation': 0.9466526958533805, 'skin': 47.3994735144993, 'total': 0.00013064408520531637}}`
