### ISSUE TITLE
Error when using demo code

### ISSUE THREAD

**Issue by kaypon** [smartcrop/smartcrop.py#21]
I've attempted to modify the demo code in order to loop through a large list of images and smart crop them automatically.

When I modify the demo code, I have the following: 

```
import json
import sys

import smartcrop
from PIL import Image

image = Image.open('999.jpg')

sc = smartcrop.SmartCrop()
result = sc.crop(image, 1440, 960)

print(json.dumps(result, indent=2))
```

I get the following in console: 

```
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Image is not JSON serializable
```

If I look at the json that comes out from `result` I see it has the `analyse_image` property, I've attempted commenting the print out, and saving the `analyse_image` with `result['analyse_image'].save("test.jpg")` it saves the analysed image (the green heat map one), but does not save the cropped image. 

Am I supposed to use the coordinates provided in the json and crop it myself thereafter? (I might of just answered my question)

**Comment by davidfischer-ch** [comment]
Hello,

Thank you for having pointed out an error in demo code.

Your answer sits here :
https://github.com/smartcrop/smartcrop.py/blob/85b38db2a6716f1213471b01f8d02043f783442c/smartcrop.py#L369

**Comment by vlasvlasvlas** [comment]
so, whats the answer here? i got the same issue :(
