### ISSUE TITLE
avoid rotation

### ISSUE THREAD

**Issue by vlasvlasvlas** [smartcrop/smartcrop.py#24]
Hi, i was testing the cli and python script version, and it the out rotates the output image when I resize it

how can i avoid rotation of image? i only need crop, not rotation.

thanks!

example
smartcroppy --width 1440 --height 1080 img_02.jpg img_02_output.jpg

input:
![img_02](https://user-images.githubusercontent.com/4071796/156441936-05e7e1ce-0281-4f52-89f7-f85489c262fd.jpg)

output:
![img_02_output](https://user-images.githubusercontent.com/4071796/156442034-eaf71cb5-9f4e-49fc-82ec-35b2f95c9448.jpg)

**Comment by davidfischer-ch** [comment]
I am guessing, but I think the CLI is either dropping Exif metadata (e.g. rotation) or either applying it. Please inspect it and provide me feedback.

**Comment by vlasvlasvlas** [comment]
txs!

**Comment by davidfischer-ch** [comment]
I am working on a fix for this.

**Comment by davidfischer-ch** [comment]
It should be fixed with "smartcrop>=0.4.0"

**Comment by deldesir** [comment]
Hi, I am using v0.4.0. Using it on "vertical" .JPG or .JPEG erroneously rotates the cropped image by 90 degrees. PNG files are OK.

**Comment by holta** [comment]
> It should be fixed with "smartcrop>=0.4.0"

FYI `smartcrop>=0.4.0` doesn't work to avoid the rotation bug — the image is erroneously rotated by 90 degrees with every "vertically oriented" JPEG 😢

@davidfischer-ch would you have any other suggestions we should try?

Testing Context: **smartcrop 0.4.0** is being used with Python 3.10.2 on Ubuntu 22.04

**Comment by holta** [comment]
Thanks to @thadk who writes:

> I suspect the solution is to try to use [PIL.ImageOps.exif_transpose](https://pillow.readthedocs.io/en/latest/reference/ImageOps.html#PIL.ImageOps.exif_transpose) before passing the image to SmartCrop to transform and then remove the orientation flag:
https://stackoverflow.com/a/30462851

- deldesir/calibre-web#21
