### ISSUE TITLE
Image has wrong mode

### ISSUE THREAD

**Issue by EdGrossman** [smartcrop/smartcrop.py#26]
Hello,

Using smartcrop 0.3.3 I'm trying to crop this image 

https://rpaexplore-donotdelete-pr-bmbsoouqp7o8ib.s3.us.cloud-object-storage.appdomain.cloud/etgtmbXSselqWimage002.png

 to Instagram standards. My python call is
`        image = sc.crop(image, w, h)`

where w = 866, h=455

I'm getting this error:
`(<class 'ValueError'>, ValueError('image has wrong mode'), <traceback object at 0x10786f300>)`

Here's the stack starting from smartcrop:
```
convert, Image.py:919
analyse, smartcrop.py:92
crop, smartcrop.py:166
```

Please suggest any fixes.

**Comment by davidfischer-ch** [comment]
I am trying to guess the issue.
One fix could be to convert the image with Pillow from the wrong mode(indexed colors ?) to the good one (rgba) ? And then call the algorithm.

**Comment by EdGrossman** [comment]
Thank you. That was the pointer I needed. I converted the image from RGBA to RGB and that solved it.
