### ISSUE TITLE
how save image in python

### ISSUE THREAD

**Issue by amofogh** [smartcrop/smartcrop.py#31]
Hi,
how to save result that cropped 
`import json
import sys
import smartcrop
from PIL import Image

image = Image.open('/.../nature-py8qzsofua447me6.jpg')
cropper = smartcrop.SmartCrop()
result = cropper.crop(image, 100, 100)
print(result)

cropper.save('/.../2.jpg')`

**Comment by davidfischer-ch** [comment]
Dear @amofogh,

How can I help you ?

**Comment by amofogh** [comment]
I found it thank you for who's don't know how to save resulted image follow like cli.py file in project [https://github.com/smartcrop/smartcrop.py/blob/master/smartcrop/cli.py](cli.py)
