### ISSUE TITLE
Interested in improvements and further developement?

### ISSUE THREAD

**Issue by jrast** [smartcrop/smartcrop.py#5]
Hi @hhatto,

Are you still interested in this project? @davidfischer-ch and me performed a code cleanup and some improvements over at https://github.com/davidfischer-ch/smartcrop.py.

If there is still interest on your side, i think it would be good to merge back these changes.

**Comment by hhatto** [comment]
Hi @jrast @davidfischer-ch

I'm not interested in this project now. Also it does not maintain active.
If you are okay, I would like to archive this repository and direct it to your repository.

**Comment by davidfischer-ch** [comment]
Hi @hhatto,

As an amateur photographer using this library for both personal and professional projects, I would like to take the responsibility of maintaining it. If @jrast is also motivated by the idea, we can setup an organization for this project (is it overkill ?).

What do you think @hhatto and @jrast ?

**Comment by jrast** [comment]
In the long term, a organization might be the best option. It's easier if new contributors are willing to participate or if the lead of the project changes.

**Comment by hhatto** [comment]
I created https://github.com/smartcrop orgnization, and moved from hhatto/smartcrop.py to smartcrop/smartcrop.py.

I invited @jrast and @davidfischer-ch as owners.

**Comment by jrast** [comment]
Closing this, as the repo has now a new home
