### ISSUE TITLE
Runnable script

### ISSUE THREAD

**Issue by nhnminh** [smartcrop/smartcrop.py#7]
Hello, in the instruction, you say that to run Smartcrop CLI, we should run 

`smartcrop.py FILE`

but actually, it doesn't work with me. I run successfully by this command instead 

`smartcroppy FILE`

Hope it helps.

**Comment by davidfischer-ch** [comment]
Hello, @nhnminh please feel free to make a pull request with the quick fix.
Thank you very much for catching this.

**Comment by davidfischer-ch** [comment]
Fixed!
